version: "3"

services:
  supermarket-server:
    image: supermarket-server
    command: npm run dev
    build: Server
    volumes:
      - ./Server:/usr/src/app
      - /usr/src/app/node_modules
    container_name: supermarket-server
    ports:
      - 3000:3000
    environment:
      ENVIRONMENT: development
    depends_on:
      - supermarket-psqldb

  supermarket-psqldb:
    image: postgres:12-alpine
    container_name: supermarket-psqldb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cmov
      - POSTGRES_PASSWORD=cmov
      - POSTGRES_DB=supermarket

  supermarket-pgadmin:
    image: thajeztah/pgadmin4
    container_name: supermarket-pgadmin
    ports:
      - 5050:5050
    depends_on:
      - supermarket-psqldb
